# Generated by Django 6.0.3 on 2026-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_social_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social Platforms'},
        ),
    ]
