# Generated by Django 6.0.3 on 2026-03-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_social_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
    ]
